### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by Nortank12** [asdfzdfj/deepcool-ld-digital-hidapi#1]
Hey,
I started to develop a CLI program in Rust similar to Deepcool Digital in Windows and I plan to support as many devices as possible. I'd like to ask you if you want to collaborate and are willing to test or -if you know Rust- help to develop the code to have a fully working and easy to use lightweight alternative to the Windows version.

So far it only supports the AK series but if you can test it, I'll add support for the LD series and fix potential bugs that I may have.
You can hit me up on Discord if you're interested. My username is nortank12.

Here's the repo: [https://github.com/Nortank12/deepcool-digital-linux](https://github.com/Nortank12/deepcool-digital-linux)

**Comment by asdfzdfj** [comment]
thanks for taking interest!

initially I intend to have the work in this repo be integrated into the existing [deepcool-digital-info](https://github.com/Algorithm0/deepcool-digital-info) repo if you somehow haven't seen that already, as that one seems to have the most (more than just AK series cooler) device support so far, and also an attempt to consolidate the efforts rather than having multiple services/projects that all supports different but specific devices although they're from the same vendor, all with different quality and its own quirks and such (speaking of which, it may be a good idea to also contact the above repo for collaboration or at least re-implementing support for devices that they have)

that said, feel free to implement the LD series cooler support in your project based on the implementation I have in this repo, and a little attribution/link to this repo would be highly appreciated

I should be able to help test your implementation when you add it, though I should note that the machine I have with this cooler attached mainly runs FreeBSD (although it's FreeBSD/Linux dual booted) so it may take some time to respond, and I don't know the relative safety of not damaging my display by sending malformed packets to it, but with what I have right now it should works fine and relatively safe

in terms of code contribution, my knowledge of Rust is beginner at best, so I might not be able to help much here, but if there's any part that looks like I might be able to help then I'll probably make a PR to your repo

**Comment by Nortank12** [comment]
Yes, I have seen that repo and tried to use it, but it seemed too complicated to set up. So I ended up copying the important parts and playing around with the device in Python to see if I could display data. And yes, you can send any weird and malformed data without causing any harm to the device.

Then I looked up if I could read CPU temp directly from Linux and indeed I can. Then I found a small Rust library that reads CPU utilization and calculates the average between 2 measurements.

So my plan was to create a simple binary in Rust that is as lightweight as possible and requires no setup, like the Python repo, and has the same functionalities as the original software.

And since I've seen no commit on that repo for months, I thought that it was dead so I created my repo and made a [Reddit post](https://www.reddit.com/r/linux_gaming/comments/1djpz73/display_software_for_anyone_with_a_deepcool_cpu/) hoping that I can reach more people. I also put credit to the other two repos that I found useful.

I found yours by searching on "deepcool" in GitHub and thought it could be a great opportunity to work a little more on my code.

### About the present:
I'm glad that you can help me test the code and obviously, I will put your credit there for testing and providing information.

I found out how to read CPU power draw. There is a file called `/sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj` which seems to be available on both Intel and AMD systems. It prints out the energy consumed in µJ which can be converted to Watts if measured twice.

I will create a separate branch, where I write a simplified version for you to test all functionalities, then I will update the main branch (and reorganize my code a little bit). And I will keep you updated here if I'm stuck somewhere or the code is ready for testing.

**Comment by asdfzdfj** [comment]
all right, though in any case I think further discussion should be moved to your repo, I'll make an issue for it

> I will create a separate branch, where I write a simplified version for you to test all functionalities, then I will update the main branch (and reorganize my code a little bit). And I will keep you updated here if I'm stuck somewhere or the code is ready for testing.

appreciated, but perhaps consider using [cargo features](https://doc.rust-lang.org/cargo/reference/features.html) to make a kind of static build where it doesn't gather system metrics but instead supplied static values suitable for testing hardware support? I think this is better than having to make a new branch and a simplified version just for me to be able to test

**Comment by Nortank12** [comment]
To properly implement support for your device (and others in the future) I have to change the structure of my code anyway, so for me, it's easier to make a quick test build and then implement it when I have more time.

> all right, though in any case I think further discussion should be moved to your repo, I'll make an issue for it

Good idea, thanks.
